### ISSUE TITLE
Pull to Refresh, Back Button and updating to Gradle 3

### ISSUE THREAD

**Issue by fabOnReact** [HiKumho/milog-android#1]
Hello HiKumho,

Thanks for you AMAZING github Project. Just wanted to open the discussion with you about a couple of things that I noticed after working on the forked version of your project.

https://github.com/fabriziobertoglio1987/sprachspiel-android/commits/master

First thing I noticed is that you do not use the Standard Pull to Refresh from the Turbolinks Android Library. I disabled this for my app in my commit.

I had to upgrade the Turbolinks-Android library
https://github.com/fabriziobertoglio1987/sprachspiel-android/commit/6a6e249386e86fb0aa2257d2c7cb22bbfd5963ff

Then remove some of your functionalities
https://github.com/fabriziobertoglio1987/sprachspiel-android/commit/26fcbe05bd9e5b4b2f587cea1b3253aaa8d443dd

As in my app, I want to display the full menu in most of my pages, I had some problems with the back button so I fixed this like that. I wonder if in your app the back button works for going back in the history.

https://github.com/fabriziobertoglio1987/sprachspiel-android/commit/3882ade9792ab54513babc3be07ea2843322bff4

Also I noticed that I can not update to Gradle 3 because It will severely break this dependencies

```
import android.support.v4.view.GravityCompat;
import android.support.v4.view.MenuItemCompat;
import android.support.v4.widget.DrawerLayout;
import android.support.v4.widget.SwipeRefreshLayout;
import android.support.v7.app.ActionBarDrawerToggle;
import android.support.v7.widget.SearchView;
import android.support.v7.widget.Toolbar;
```

I just thought of starting a discussion, maybe we could find something interesting and you for sure have better understanding of this then me

Thanks a lot for this project
Happy Holidays
Fabrizio Bertoglio

**Comment by jinhucheung** [comment]
@fabriziobertoglio1987 Thanks for your feedback, I will reply to you as soon :)

**Comment by jinhucheung** [comment]
Hello fabriziobertoglio1987,

I don't use the TurbolinksSwipeRefreshLayout from the Turbolinks-Android Library, because it is faild to upgrade 1.0.3 version in my local environment (Ubuntu 14.04 x86)

I have upgraded the Turbolinks-Android Library to 1.0.3 version now

[HiKumho/milog-android@ecc3554e5b13e37f39d8a054d7b2bee4245ac472](https://github.com/HiKumho/milog-android/commit/ecc3554e5b13e37f39d8a054d7b2bee4245ac472)

Then in my app, the back button works  for going back. The MainActivity is root in my app, and the EmptyActivity is a node that open a link.

[HiKumho/milog-android@BaseActivity.java#L128](https://github.com/HiKumho/milog-android/blob/master/app/src/main/java/me/hijinhu/milog/activities/BaseActivity.java#L128)

Aslo I have upgraded the Gradle 3 by this (official tutorial) [https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html], I hope to be useful to you

[HiKumho/milog-android@e1f8087b97ddb7e1b579a30768ff4962f91f0172](https://github.com/HiKumho/milog-android/commit/e1f8087b97ddb7e1b579a30768ff4962f91f0172
)

Thanks for your feedback:)
Happy new year
jinhu cheung

**Comment by fabOnReact** [comment]
Hello @HiKumho ,

thanks a lot for your reply and your amazing opensource project.. My project is almost finished, right now I am rewriting the backend then I will publish the app.

My Ubuntu Version is 16.04.3 (Xenial)

Ok for the other points, updating gradle I'll need a couple of days and I'll come back to you.. Probably I broke something with the back button, but this are my observation:

I quote the [Turbolinks 5 documentation](https://github.com/turbolinks/turbolinks#application-visits)

```
The default visit action is advance. During an advance visit, Turbolinks pushes a new entry onto the browser’s history stack using history.pushState.

Applications using the Turbolinks iOS adapter typically handle advance visits by pushing a new view controller onto the navigation stack. Similarly, applications using the Android adapter typically push a new activity onto the back stack.

```
so I noticed you do AJAX request for logging out like this

https://github.com/fabriziobertoglio1987/sprachspiel-android/blob/master/app/src/main/java/me/hijinhu/milog/activities/MainActivity.java#L216

In addition I thought of using the `visitProposedToLocationWithAction(HOST_URL, ACT_REPLACE);`

From my understanding this somehow edit the browser history, avoiding the user to go back on those pages where he was logged in.

I am not expert and do not still have a full understanding of Java/Android and Turbolinks-Android, but I look forward in learning more..

Thanks a lot
Happy new year 
Fabrizio Bertoglio

**Comment by fabOnReact** [comment]
@HiKumho  also I saw that you tried my game so thanks a lot for being a part of it. It is still in early development and I'll publish a new version and maybe in the future also an english version.

**Comment by jinhucheung** [comment]
Hi @fabriziobertoglio1987,

I apologize for my late reply. I am not an expert either, so I did some work.

As you say, turbolinks replaces current browser history by a replace visit. 

In my app, the backend receives a signout request, it redirects root path. The turbolins android adpater will detect and handle this path. 

[turbolinks/turbolinks-android/TurbolinksSession.java#L122](https://github.com/turbolinks/turbolinks-android/tree/master/turbolinks/src/main/java/com/basecamp/turbolinks#L122)

[WebViewClient#shouldOverrideUrlLoading](https://developer.android.com/guide/webapps/webview.html#HandlingNavigation)

I think that it is better solution :)

Thank you for your interest in this app.
Look forward to your app as soon as publish~
jinhu cheung

**Comment by fabOnReact** [comment]
@HiKumho yes. I believe you are right and that you have a deeper understanding of the AndroidSdk. I wish to work more on this project and I will in a couple of months submit a pull request if I do end up developing some cool features. I just forked your repository, I have already 3 apps that use Turbolinks 5 and Rails 5 so I ll working on Turbolinks-Android and Milog-Android.

Thanks a lot 
Best Regards
Fabrizio Bertoglio

**Comment by jinhucheung** [comment]
@fabriziobertoglio1987 ok,  I look forward to seeing your pull request as soon as possible :)

Best Regards
jinhu cheung
